services:
  - type: web
    name: bitpan
    runtime: docker
    branch: main
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: NOVA_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
